# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build & Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REACT_APP_SCOUT_API_URI: 'http://localhost:5000/graphql'
  REACT_APP_SCOUT_CLIENT_URI: 'http://localhost:3000'
  REACT_APP_SCOUT_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
  REACT_APP_SCOUT_AZURE_APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  REACT_APP_SCOUT_AZURE_AUTHORITIES: 'twosigmadataclinic.b2clogin.com'
  REACT_APP_SCOUT_AZURE_FULL_AUTHORITY_URL: 'https://twosigmadataclinic.b2clogin.com/twosigmadataclinic.onmicrosoft.com/B2C_1_scout_signup_signin'
  REACT_APP_SCOUT_AZURE_B2C_SCOPES: 'https://twosigmadataclinic.onmicrosoft.com/scout-dev-api/Scout.API'
  SCOUT_SERVER_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
  SCOUT_SERVER_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
  SCOUT_SERVER_AZURE_APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  SCOUT_SERVER_AZURE_B2C_AUTH_POLICY_NAME: 'B2C_1_scout_signup_signin'
  SCOUT_SERVER_AZURE_B2C_IDENTITY_METADATA_URI: 'https://twosigmadataclinic.b2clogin.com/twosigmadataclinic.onmicrosoft.com/v2.0/.well-known/openid-configuration'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run frontend build
      run: yarn build
      working-directory: packages/frontend
    - name: Run frontend tests
      run: yarn test
      working-directory: packages/frontend
    - name: Run server build
      run: yarn build
      working-directory: packages/server
# TODO: need to add server tests
