# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    licensed:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: jonabc/setup-licensed@v1
          with:
            version: 2.x
        - run: npm install # install your projects dependencies in local environment
        - id: licensed
          uses: jonabc/licensed-ci@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/github-script@0.2.0
          if: always() && steps.licensed.outputs.pr_number
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              github.issues.createComment({
                ...context.repo,
                issue_number: ${{ steps.licensed.outputs.pr_number }}
                body: 'My custom PR message'
              })
